name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7 # or the Ruby version you're using

    - name: Update RubyGems
      run: gem update --system 3.3.22

    - name: Install dependencies
      run: bundle install

    - name: Build the Jekyll site
      run: bundle exec jekyll build

    - name: Deploy the site
      run: bundle exec jekyll deploy
